#pragma once

extern void init();
extern void BRK();
extern void RTI();
extern void RTS();
extern void PHP();
extern void CLC();
extern void PLP();
extern void SEC();
extern void CLI();
extern void PLA();
extern void SEI();
extern void DEY();
extern void TYA();
extern void TAY();
extern void CLV();
extern void INY();
extern void CLD();
extern void INX();
extern void SED();
extern void TXA();
extern void TXS();
extern void TAX();
extern void TSX();
extern void DEX();
extern void JMP(uint16_t imm);
extern void BPL(int8_t imm);
extern void JSR(uint16_t imm);
extern void BMI(int8_t imm);
extern void BVC(int8_t imm);
extern void BVS(int8_t imm);
extern void BCC(int8_t imm);
extern void LDY(uint16_t imm);
extern void BCS(int8_t imm);
extern void CPY(uint8_t imm);
extern void BNE(int8_t imm);
extern void CPX(uint8_t imm);
extern void BEQ(int8_t imm);